name: CDK Application

on:
  push:
    branches:
      - feature/cdk
    
env:
  CDK_LOCAL_FOLDER: ./ba-cloud-academy-github-cdk-olliethorpe

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install AWS CDK
        run: |
          npm install -g aws-cdk

      - name: Install Python dependencies
        working-directory: ${{ env.CDK_LOCAL_FOLDER }} 
        run: |
          python -m pip install -r requirements.txt
          
      - name: synth CDK
        working-directory: ${{ env.CDK_LOCAL_FOLDER }} 
        run: |
          cdk synth

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cloudformation-template
          path: ./ba-cloud-academy-github-cdk-olliethorpe/cdk.out/

  verify:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download cloudformation-template
        uses: actions/download-artifact@v3
        with:
          name: cloudformation-template
          path: ~/artifacts

      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Validate cloudformation template
        shell: bash
        id: validation
        run: |
          cd ~/artifacts
          aws cloudformation validate-template --template-body file://BaCloudAcademyGithubCdkOlliethorpeStack.template.json
          if [ $? -eq 0 ]; then
            validationStatus="success"
          else
            validationStatus="failure"
          fi
          echo "VSTATUS=$validationStatus" >> $GITHUB_OUTPUT
          echo $VSTATUS
        
 
  deploy:
    needs: verify
    runs-on: ubuntu-latest
    if: ${{ needs.verify.steps.validation.VSTATUS == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install AWS CDK
        run: |
          npm install -g aws-cdk

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Python dependencies
        working-directory: ${{ env.CDK_LOCAL_FOLDER }}
        run: |
          python -m pip install -r requirements.txt
          
      - name: Deploy to AWS
        working-directory: ${{ env.CDK_LOCAL_FOLDER }} 
        run: |
          cdk deploy --require-approval never

    