name: Run Python Script

on:
  push

jobs:
  build-artefacts:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: create artifacts
        working-directory: './scripts'
        run: |
          python my_script.py

      - uses: actions/upload-artifact@v3
        with:
          name: my-text-artefact
          path: artifacts/my_text_file.txt
          
  
  print-artefact:
    runs-on: ubuntu-latest
    needs: build-artefacts
    steps:
      - name: download artefact
        uses: actions/download-artifact@v3
        with:
          name: my-text-artefact
          path: ./artifacts/my_text_file.txt

      - name: echo artefact
        shell: bash
        working-directory: ./artifacts
        run: |
          cat my_text_file.txt
        
        
